<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Nationalities
    |--------------------------------------------------------------------------
    |
    | The set of nationalities used in website.
    |
    */
    'nationalities' => [
        "SA" => "Saudi Arabian",
        "AF" => "Afghan",
        "AL" => "Albanian",
        "DZ" => "Algerian",
        "US" => "American",
        "AS" => "American Samoan",
        "AO" => "Angolan",
        "AI" => "Anguillian",
        "AG" => "Antiguan",
        "AR" => "Argentine",
        "AM" => "Armenian",
        "AW" => "Aruban",
        "AU" => "Australian",
        "AT" => "Austrian",
        "AZ" => "Azerbaijani",
        "BS" => "Bahamian",
        "BH" => "Bahraini",
        "BD" => "Bangladeshi",
        "BB" => "Barbadian",
        "BY" => "Belarusian",
        "BE" => "Belgian",
        "BZ" => "Belizean",
        "BJ" => "Beninese",
        "BM" => "Bermudian",
        "BT" => "Bhutanese",
        "BO" => "Bolivian",
        "BA" => "Bosnian",
        "BW" => "Botswanan",
        "BR" => "Brazilian",
        "GB" => "British",
        "VG" => "British Virgin Islander",
        "BN" => "Bruneian",
        "BG" => "Bulgarian",
        "BF" => "Burkinabe",
        "BI" => "Burundian",
        "KH" => "Cambodian",
        "CM" => "Cameroonian",
        "CA" => "Canadian",
        "CV" => "Cape Verdean",
        "KY" => "Caymanian",
        "CF" => "Central African",
        "TD" => "Chadian",
        "CL" => "Chilean",
        "CN" => "Chinese",
        "CX" => "Christmas Islander",
        "CO" => "Colombian",
        "KM" => "Comorian",
        "CD" => "Congolese",
        "CK" => "Cook Islander",
        "CR" => "Costa Rican",
        "HR" => "Croatian",
        "CU" => "Cuban",
        "CY" => "Cypriot",
        "CZ" => "Czech",
        "DK" => "Danes",
        "DJ" => "Djiboutian",
        "DM" => "Dominican",
        "NL" => "Dutch",
        "AN" => "Dutch Antillean",
        "EC" => "Ecuadorian",
        "EG" => "Egyptian",
        "AE" => "Emirati",
        "GQ" => "Equatorial Guinean",
        "ER" => "Eritrean",
        "EE" => "Estonian",
        "ET" => "Ethiopian",
        "FK" => "Falkland Islander",
        "FO" => "Faroese",
        "FJ" => "Fijian",
        "PH" => "Filipino",
        "FI" => "Finnish",
        "FR" => "French",
        "GF" => "French Guianese",
        "PF" => "French Polynesian",
        "WF" => "Futunan",
        "GA" => "Gabonese",
        "GM" => "Gambian",
        "GE" => "Georgian",
        "DE" => "German",
        "GH" => "Ghanaian",
        "GI" => "Gibraltarian",
        "GR" => "Greek",
        "GD" => "Grenadian",
        "GP" => "Guadeloupian",
        "GU" => "Guamanian",
        "GT" => "Guatemalan",
        "GN" => "Guinean",
        "GY" => "Guyanese",
        "HT" => "Haitian",
        "HN" => "Honduran",
        "HU" => "Hungarian",
        "IS" => "Icelander",
        "IN" => "Indian",
        "ID" => "Indonesian",
        "IR" => "Iranian",
        "IQ" => "Iraqi",
        "IE" => "Irish",
        "IT" => "Italian",
        "CI" => "Ivoirian",
        "JM" => "Jamaican",
        "JP" => "Japanese",
        "JO" => "Jordanian",
        "KZ" => "Kazakhstani",
        "KE" => "Kenyan",
        "KI" => "Kiribati",
        "KW" => "Kuwaiti",
        "KG" => "Kyrgyzstani",
        "LV" => "Latvian",
        "LB" => "Lebanese",
        "LR" => "Liberian",
        "LY" => "Libyan",
        "LI" => "Liechtensteiner",
        "LT" => "Lithuanian",
        "LU" => "Luxembourger",
        "MK" => "Macedonian",
        "MG" => "Malagasy",
        "MW" => "Malawian",
        "MY" => "Malaysian",
        "MV" => "Maldivian",
        "ML" => "Malian",
        "MT" => "Maltese",
        "MH" => "Marshallese",
        "MQ" => "Martiniquai",
        "MR" => "Mauritanian",
        "MU" => "Mauritian",
        "MX" => "Mexican",
        "PM" => "Miquelonnais",
        "MD" => "Moldovan",
        "MC" => "Monacan",
        "MN" => "Mongolian",
        "ME" => "Montenegrin",
        "MS" => "Montserratian",
        "MA" => "Moroccan",
        "MZ" => "Mozambican",
        "MM" => "Myanmarian",
        "NR" => "Nauruan",
        "NP" => "Nepalese",
        "NC" => "New Caledonian",
        "NZ" => "New Zealander",
        "VU" => "Ni-Vanuatu",
        "NI" => "Nicaraguan",
        "NG" => "Nigerian",
        "NE" => "Nigerien",
        "NU" => "Niuean",
        "NF" => "Norfolk Islander",
        "KP" => "North Korean",
        "MP" => "Northern Marianan",
        "NO" => "Norwegian",
        "OM" => "Omani",
        "PK" => "Pakistani",
        "PW" => "Palauan",
        "PS" => "Palestinian",
        "PA" => "Panamanian",
        "PG" => "Papuans",
        "PY" => "Paraguayan",
        "PE" => "Peruvian",
        "PL" => "Polish",
        "PT" => "Portuguese",
        "PR" => "Puerto Rican",
        "QA" => "Qatari",
        "RO" => "Romanian",
        "RU" => "Russian",
        "RW" => "Rwandan",
        "RE" => "Réunionese",
        "SH" => "Saint Helenian",
        "LC" => "Saint Lucian",
        "SV" => "Salvadoran",
        "WS" => "Samoan",
        "ST" => "Santomean",
        "SN" => "Senegalese",
        "RS" => "Serbian",
        "SC" => "Seychellois",
        "SL" => "Sierra Leonean",
        "SG" => "Singaporean",
        "SK" => "Slovak",
        "SI" => "Slovenian",
        "SB" => "Solomon Islander",
        "SO" => "Somali",
        "ZA" => "South African",
        "KR" => "South Korean",
        "ES" => "Spanish",
        "LK" => "Sri Lankan",
        "SD" => "Sudanese",
        "SR" => "Surinamer",
        "SZ" => "Swazi",
        "SE" => "Swede",
        "CH" => "Swiss",
        "SY" => "Syrian",
        "TW" => "Taiwanese",
        "TJ" => "Tajikistani",
        "TZ" => "Tanzanian",
        "TH" => "Thai",
        "TT" => "Tobagonian",
        "TG" => "Togolese",
        "TK" => "Tokelauan",
        "TO" => "Tongan",
        "TN" => "Tunisian",
        "TR" => "Turk",
        "TM" => "Turkmen",
        "TC" => "Turks and Caicos Islander",
        "TV" => "Tuvaluan",
        "UM" => "U.S. Minor Outlying Islander",
        "UG" => "Ugandan",
        "UA" => "Ukrainian",
        "UY" => "Uruguayan",
        "UZ" => "Uzbek",
        "VA" => "Vatican",
        "VE" => "Venezuelan",
        "VN" => "Vietnamese",
        "VI" => "Virgin Islander",
        "YE" => "Yemeni",
        "ZM" => "Zambian",
        "ZW" => "Zimbabwean"
    ],

    /*
    |--------------------------------------------------------------------------
    | Membership types
    |--------------------------------------------------------------------------
    |
    | The set of membership types used in website.
    |
    */
    'memberships' => [
        1 => [
            'name' => 'Full-time member',
            'price' => 250,
        ],
        2 => [
            'name' => 'Part-time member',
            'price' => 200,
        ],
        3 => [
            'name' => 'Affiliate member',
            'price' => 150,
        ],
        'delivery_fees' => 32.20
    ]
];
